### ISSUE TITLE
Module 'BouncyCastle_ObjC' not found

### ISSUE THREAD

**Issue by Antonellotti** [DimensionDev/BouncyCastle-ObjC#1]
after running 'pod install' in Example folder, the Example project still gets this error

**Comment by MainasuK** [comment]
Could you paste the error log? And you can check the pod install progress using:

```bash
cd Example/
pod install --verbose
```

**Comment by Antonellotti** [comment]
I downloaded J2ObjC manually and put in the project folder. I can see it unzipping while pods are being installed

-> Installing BouncyCastle-ObjC 0.1.0
 > Running prepare command
   $ /bin/bash -c  set -e BouncyCastle-ObjC/Scripts/download.sh
   BouncyCastle-ObjC/Scripts/generate.sh
   
   J2OBJC_VERSION="2.4"
   Fetching J2ObjC v2.4 from https://github.com/google/j2objc/releases/download/2.4/j2objc-2.4.zip
   
   if [[ -d dist ]]; then
     exit
   fi
   
   echo "Fetching J2ObjC v${J2OBJC_VERSION} from https://github.com/google/j2objc/releases/download/${J2OBJC_VERSION}/j2objc-${J2OBJC_VERSION}.zip"
   # curl -OL https://github.com/google/j2objc/releases/download/${J2OBJC_VERSION}/j2objc-${J2OBJC_VERSION}.zip
   # echo "${SHA1_CHECKSUM}  j2objc-${J2OBJC_VERSION}.zip" | shasum -c
   unzip -o -q j2objc-${J2OBJC_VERSION}.zip
   
   J2OBJC_PATH=j2objc-${J2OBJC_VERSION}
   
   mkdir dist
   mv  $J2OBJC_PATH/include \
       $J2OBJC_PATH/lib \
       $J2OBJC_PATH/frameworks \
       $J2OBJC_PATH/j2objc \
       $J2OBJC_PATH/j2objcc \
       dist
   rm -rf j2objc-${J2OBJC_VERSION} #j2objc-${J2OBJC_VERSION}.zip
   
   touch dist/VERSION
   echo $J2OBJC_VERSION > dist/VERSION
   JDK not supported. Please set JAVA_HOME to JDK 1.8 or 11.
  - Running pre install hooks

-> Removing AFNetworking

Generating Pods project
  - Creating Pods project
  - Installing files into Pods project
    - Adding source files
    - Adding frameworks
    - Adding libraries
    - Adding resources
    - Adding development pod helper files
    - Linking headers
  - Installing Pod Targets
    - Installing target `BouncyCastle-ObjC` iOS 8.0
  - Installing Aggregate Targets
    - Installing target `Pods-BouncyCastle-ObjC_Example` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Example/Pods-BouncyCastle-ObjC_Example-Info.plist`
      - Generating module map file at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Example/Pods-BouncyCastle-ObjC_Example.modulemap`
      - Generating umbrella header at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Example/Pods-BouncyCastle-ObjC_Example-umbrella.h`
      - Generating dummy source at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Example/Pods-BouncyCastle-ObjC_Example-dummy.m`
    - Installing target `Pods-BouncyCastle-ObjC_Tests` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Tests/Pods-BouncyCastle-ObjC_Tests-Info.plist`
      - Generating module map file at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Tests/Pods-BouncyCastle-ObjC_Tests.modulemap`
      - Generating umbrella header at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Tests/Pods-BouncyCastle-ObjC_Tests-umbrella.h`
      - Generating dummy source at `Pods/Target Support
      Files/Pods-BouncyCastle-ObjC_Tests/Pods-BouncyCastle-ObjC_Tests-dummy.m`
  - Generating deterministic UUIDs
  - Stabilizing target UUIDs
  - Running post install hooks
    - Podfile
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  Cleaning up sandbox directory
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-BouncyCastle-ObjC_Example` (`BouncyCastle-ObjC.xcodeproj` project)

Integrating target `Pods-BouncyCastle-ObjC_Tests` (`BouncyCastle-ObjC.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from
    `/Library/Ruby/Gems/2.3.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

Sending stats
      - BouncyCastle-ObjC, 0.1.0

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

**Comment by MainasuK** [comment]
Yeah. You can manually download J2ObjC to make it works. Closed

**Comment by Antonellotti** [comment]
but what about 'Module 'BouncyCastle_ObjC' not found' in Xcode?

**Comment by MainasuK** [comment]
> but what about "Module 'BouncyCastle_ObjC' not found" in Xcode? Example project doesn't compile. Same for my project after adding your pod

Let's me check this.

**Comment by MainasuK** [comment]
You can check the Java env for J2ObjC:
```bash
MainasuK@MacMini BouncyCastle-ObjC % java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
MainasuK@MacMini BouncyCastle-ObjC % javac -version
javac 1.8.0_121
```

Under the repo root dir. Make sure the dist exist. Then manually run generate.sh

```bash
MainasuK@MacMini BouncyCastle-ObjC % ls
BouncyCastle-ObjC		README.md
BouncyCastle-ObjC.podspec	_Pods.xcodeproj
Example				dist
LICENSE
MainasuK@MacMini BouncyCastle-ObjC % ls               
BouncyCastle-ObjC		README.md
BouncyCastle-ObjC.podspec	_Pods.xcodeproj
Example				dist
LICENSE
MainasuK@MacMini BouncyCastle-ObjC % ls                                        
BouncyCastle-ObjC		README.md
BouncyCastle-ObjC.podspec	_Pods.xcodeproj
Example				dist
LICENSE
MainasuK@MacMini BouncyCastle-ObjC % ./BouncyCastle-ObjC/Scripts/generate.sh 
MainasuK@MacMini BouncyCastle-ObjC % ls ./BouncyCastle-ObjC/Classes 
AEADAlgorithm.h
AEADAlgorithm.m
AEADBlockCipher.h
…
```

The BouncyCastle-ObjC/Classes/ dir should have lots of files translated by J2ObjC. Then use pod install generate valid pod for project
```bash
cd Example/
pod install
```

I hope that helps.

**Comment by MainasuK** [comment]
Fixed in https://github.com/DimensionDev/BouncyCastle-ObjC/commit/50ab1905bc7ce2f9dc59c2cab68d1af35fd37bb3

**Comment by Antonellotti** [comment]
dist folder has 4.58 Gb 
generate script returns:
### 
user$ ./generate.sh
find: ./BouncyCastle-ObjC/src: No such file or directory
./generate.sh: line 11: dist/j2objc: No such file or directory
cp: ./BouncyCastle-ObjC/Template/BouncyCastle-ObjC_template.h: No such file or directory

Classes folder is empty

**Comment by MainasuK** [comment]
Not the run the scripts under ./Scripts/ folder. This script is used by the cocoapods. If you manually trigger it. Use `./BouncyCastle-ObjC/Scripts/generate.sh` likes https://github.com/DimensionDev/BouncyCastle-ObjC/issues/1#issuecomment-549702190

**Comment by Antonellotti** [comment]
It says my JDK not supported. I have 12.0.2

JDK not supported. Please set JAVA_HOME to JDK 1.8 or 11.

**Comment by MainasuK** [comment]
> JDK not supported. Please set JAVA_HOME to JDK 1.8 or 11.

You can use OpenJDK 1.8 or 11.
And  please check the requirements about J2ObjC: https://github.com/google/j2objc#requirements
